packages:
  - packages/types
  - packages/utils
  - packages/redux-adapter
  - packages/examples/basic-example-counter
  - packages/examples/complete-example-shopping-list

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  ajv@<8.18.0: '>=8.18.0'
  minimatch@<10.2.1: '>=10.2.1'
